-- Booking payments (short-stay guest charges) — separate from campaign `payments` table.
-- Host M-Pesa payout profile + Paystack transfer ledger.

-- ---------------------------------------------------------------------------
-- booking_payments
-- ---------------------------------------------------------------------------
DO $$ BEGIN
  CREATE TYPE booking_payment_status AS ENUM (
    'pending',
    'processing',
    'success',
    'failed',
    'refunded'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS booking_payments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  property_id UUID NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
  host_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  payer_user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  scheduled_visit_id UUID REFERENCES scheduled_visits(id) ON DELETE SET NULL,

  paystack_reference TEXT NOT NULL,
  amount_requested_minor BIGINT NOT NULL,
  amount_paid_minor BIGINT,
  platform_fee_minor BIGINT NOT NULL DEFAULT 0,
  host_net_minor BIGINT NOT NULL,
  currency TEXT NOT NULL DEFAULT 'KES',

  status booking_payment_status NOT NULL DEFAULT 'pending',

  customer_email TEXT NOT NULL,
  customer_name TEXT,
  metadata JSONB NOT NULL DEFAULT '{}',

  paid_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT booking_payments_paystack_reference_unique UNIQUE (paystack_reference),
  CONSTRAINT booking_payments_amounts_non_negative CHECK (
    amount_requested_minor >= 0
    AND (amount_paid_minor IS NULL OR amount_paid_minor >= 0)
    AND platform_fee_minor >= 0
    AND host_net_minor >= 0
  )
);

CREATE INDEX IF NOT EXISTS idx_booking_payments_property_id ON booking_payments(property_id);
CREATE INDEX IF NOT EXISTS idx_booking_payments_host_id ON booking_payments(host_id);
CREATE INDEX IF NOT EXISTS idx_booking_payments_status ON booking_payments(status);
CREATE INDEX IF NOT EXISTS idx_booking_payments_payer ON booking_payments(payer_user_id);
CREATE INDEX IF NOT EXISTS idx_booking_payments_scheduled_visit ON booking_payments(scheduled_visit_id);

-- ---------------------------------------------------------------------------
-- scheduled_visits: link to booking payment (nullable for legacy rows)
-- ---------------------------------------------------------------------------
ALTER TABLE scheduled_visits
  ADD COLUMN IF NOT EXISTS booking_payment_id UUID REFERENCES booking_payments(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_scheduled_visits_booking_payment_id ON scheduled_visits(booking_payment_id);

-- ---------------------------------------------------------------------------
-- host_payment_profiles — M-Pesa / Paystack recipient (Kenya)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS host_payment_profiles (
  host_id UUID PRIMARY KEY REFERENCES profiles(id) ON DELETE CASCADE,
  mpesa_phone TEXT NOT NULL DEFAULT '',
  account_holder_name TEXT,
  -- Paystack mobile_money: provider code from GET /bank?currency=KES&type=mobile_money (e.g. Safaricom)
  mpesa_provider_code TEXT,
  paystack_recipient_code TEXT,
  payout_currency TEXT NOT NULL DEFAULT 'KES',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- host_transfers — withdrawals to host M-Pesa (Paystack Transfer API)
-- transfer_reference: UUID v4 generated by Edge Function (Paystack-compatible)
-- ---------------------------------------------------------------------------
DO $$ BEGIN
  CREATE TYPE host_transfer_status AS ENUM (
    'pending',
    'queued',
    'processing',
    'success',
    'failed',
    'rejected',
    'otp_required'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS host_transfers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  host_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  amount_minor BIGINT NOT NULL,
  currency TEXT NOT NULL DEFAULT 'KES',
  transfer_reference TEXT NOT NULL,
  paystack_transfer_code TEXT,
  paystack_transfer_numeric_id BIGINT,
  recipient_code_snapshot TEXT,
  status host_transfer_status NOT NULL DEFAULT 'pending',
  reason TEXT,
  failure_reason TEXT,
  metadata JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT host_transfers_reference_unique UNIQUE (transfer_reference),
  CONSTRAINT host_transfers_amount_positive CHECK (amount_minor > 0)
);

CREATE INDEX IF NOT EXISTS idx_host_transfers_host_id ON host_transfers(host_id);
CREATE INDEX IF NOT EXISTS idx_host_transfers_status ON host_transfers(status);
CREATE INDEX IF NOT EXISTS idx_host_transfers_created ON host_transfers(created_at DESC);

-- ---------------------------------------------------------------------------
-- Triggers: updated_at
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION touch_booking_payments_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_booking_payments_updated ON booking_payments;
CREATE TRIGGER trg_booking_payments_updated
  BEFORE UPDATE ON booking_payments
  FOR EACH ROW EXECUTE FUNCTION touch_booking_payments_updated_at();

CREATE OR REPLACE FUNCTION touch_host_payment_profiles_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_host_payment_profiles_updated ON host_payment_profiles;
CREATE TRIGGER trg_host_payment_profiles_updated
  BEFORE UPDATE ON host_payment_profiles
  FOR EACH ROW EXECUTE FUNCTION touch_host_payment_profiles_updated_at();

CREATE OR REPLACE FUNCTION touch_host_transfers_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_host_transfers_updated ON host_transfers;
CREATE TRIGGER trg_host_transfers_updated
  BEFORE UPDATE ON host_transfers
  FOR EACH ROW EXECUTE FUNCTION touch_host_transfers_updated_at();

-- ---------------------------------------------------------------------------
-- Validate scheduled_visit.booking_payment_id matches success + property
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION validate_scheduled_visit_booking_payment()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.booking_payment_id IS NOT NULL THEN
    IF NOT EXISTS (
      SELECT 1 FROM booking_payments bp
      WHERE bp.id = NEW.booking_payment_id
        AND bp.status = 'success'
        AND bp.property_id = NEW.property_id
    ) THEN
      RAISE EXCEPTION 'booking_payment_id must reference a successful booking_payment for this property';
    END IF;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_scheduled_visits_booking_payment ON scheduled_visits;
CREATE TRIGGER trg_scheduled_visits_booking_payment
  BEFORE INSERT OR UPDATE OF booking_payment_id, property_id ON scheduled_visits
  FOR EACH ROW EXECUTE FUNCTION validate_scheduled_visit_booking_payment();

-- ---------------------------------------------------------------------------
-- Link booking payment row to visit after insert (reference must match)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.link_booking_payment_to_visit(
  p_payment_id UUID,
  p_visit_id UUID,
  p_reference TEXT
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  updated_count INT;
BEGIN
  UPDATE booking_payments bp
  SET scheduled_visit_id = p_visit_id
  WHERE bp.id = p_payment_id
    AND bp.paystack_reference = p_reference
    AND bp.status = 'success'
    AND bp.scheduled_visit_id IS NULL;

  GET DIAGNOSTICS updated_count = ROW_COUNT;
  RETURN updated_count > 0;
END;
$$;

REVOKE ALL ON FUNCTION public.link_booking_payment_to_visit(UUID, UUID, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.link_booking_payment_to_visit(UUID, UUID, TEXT) TO anon;
GRANT EXECUTE ON FUNCTION public.link_booking_payment_to_visit(UUID, UUID, TEXT) TO authenticated;

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------
ALTER TABLE booking_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE host_payment_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE host_transfers ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Hosts view own booking receipts" ON booking_payments;
CREATE POLICY "Hosts view own booking receipts" ON booking_payments
  FOR SELECT USING (auth.uid() = host_id);

DROP POLICY IF EXISTS "Payers view own booking payments" ON booking_payments;
CREATE POLICY "Payers view own booking payments" ON booking_payments
  FOR SELECT USING (auth.uid() IS NOT NULL AND auth.uid() = payer_user_id);

DROP POLICY IF EXISTS "Host manages payment profile" ON host_payment_profiles;
DROP POLICY IF EXISTS "Host select payment profile" ON host_payment_profiles;
DROP POLICY IF EXISTS "Host insert payment profile" ON host_payment_profiles;
DROP POLICY IF EXISTS "Host update payment profile" ON host_payment_profiles;
DROP POLICY IF EXISTS "Host delete payment profile" ON host_payment_profiles;

CREATE POLICY "Host select payment profile" ON host_payment_profiles
  FOR SELECT USING (auth.uid() = host_id);

CREATE POLICY "Host insert payment profile" ON host_payment_profiles
  FOR INSERT WITH CHECK (auth.uid() = host_id);

CREATE POLICY "Host update payment profile" ON host_payment_profiles
  FOR UPDATE USING (auth.uid() = host_id) WITH CHECK (auth.uid() = host_id);

CREATE POLICY "Host delete payment profile" ON host_payment_profiles
  FOR DELETE USING (auth.uid() = host_id);

DROP POLICY IF EXISTS "Host views own transfers" ON host_transfers;
CREATE POLICY "Host views own transfers" ON host_transfers
  FOR SELECT USING (auth.uid() = host_id);

-- No direct INSERT/UPDATE on host_transfers from clients — Edge Functions use service role.

GRANT SELECT ON booking_payments TO authenticated;
GRANT SELECT ON host_payment_profiles TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON host_payment_profiles TO authenticated;

COMMENT ON TABLE booking_payments IS 'Short-stay guest charges (separate from campaign payments table).';
COMMENT ON TABLE host_payment_profiles IS 'Host M-Pesa / Paystack transfer recipient configuration (Kenya).';
COMMENT ON TABLE host_transfers IS 'Host withdrawals via Paystack Transfers; transfer_reference is UUID v4 from Edge.';

-- Allow guests (no auth) to complete a short-stay booking when payment is already verified.
DROP POLICY IF EXISTS "Guest insert visit with verified booking payment" ON scheduled_visits;
CREATE POLICY "Guest insert visit with verified booking payment" ON scheduled_visits
  FOR INSERT WITH CHECK (
    booking_payment_id IS NOT NULL
    AND EXISTS (
      SELECT 1 FROM booking_payments bp
      WHERE bp.id = booking_payment_id
        AND bp.status = 'success'
        AND bp.property_id = property_id
    )
  );
GRANT SELECT ON host_transfers TO authenticated;
